backend:
  name: github
  repo: updazenews/updazenews.github.io
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow

collections:
  - name: "articles"
    label: "Articles"
    folder: "articles"
    create: true
    slug: "{{slug}}"
    extension: "html"
    format: "yaml-frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "string", default: "general" }
      - { label: "Author", name: "author", widget: "string", default: "Updaze Desk" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
